In [ ]:
# Read the csv file using pandas.

import pandas as pd

file_path = r"C:\Users\Ravi\Downloads\FAOSTAT_data - FAOSTAT_data_en_12-29-2024.csv"

df = pd.read_csv(file_path)

df.head()

,Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Item Code (CPC),Item,Year Code,Year,Unit,Value,Flag,Flag Description,Note
0,QCL,Crops and livestock products,4,Afghanistan,5312,Area harvested,1371,"Almonds, in shell",2019,2019,ha,29203.0,A,Official figure,NaN
1,QCL,Crops and livestock products,4,Afghanistan,5412,Yield,1371,"Almonds, in shell",2019,2019,kg/ha,1308.3,A,Official figure,NaN
2,QCL,Crops and livestock products,4,Afghanistan,5510,Production,1371,"Almonds, in shell",2019,2019,t,38205.0,A,Official figure,NaN
3,QCL,Crops and livestock products,4,Afghanistan,5312,Area harvested,1371,"Almonds, in shell",2020,2020,ha,22134.0,A,Official figure,NaN
4,QCL,Crops and livestock products,4,Afghanistan,5412,Yield,1371,"Almonds, in shell",2020,2020,kg/ha,1775.9,A,Official figure,NaN

In [ ]:
df.tail()

In [ ]:
# Check the shape of the data.

df.shape

(224647, 15)

In [ ]:
df.info()
df.describe()

In [ ]:
df.isna().sum()

In [ ]:
# Check the unique values of area.

df['Area'].unique().tolist()

['Area harvested',
 'Yield',
 'Production',
 'Stocks',
 'Producing Animals/Slaughtered',
 'Laying',
 'Yield/Carcass Weight',
 'Milk Animals']

In [ ]:
# Check the unique values of elements.

df['Element'].unique().tolist()

['Area harvested',
 'Yield',
 'Production',
 'Stocks',
 'Producing Animals/Slaughtered',
 'Laying',
 'Yield/Carcass Weight',
 'Milk Animals']

In [ ]:
# Step 1: Keep only needed columns.

df = df[["Area", "Item", "Year", "Element", "Value"]]


# Step 2: Filter crop-related elements.

crop_elements = ["Area harvested", "Yield", "Production"]
df_crop = df[df["Element"].isin(crop_elements)]

# Step 3: Covert the data into Pivot table.

df_wide = df_crop.pivot_table(
    index=["Area", "Item", "Year"],
    columns="Element",
    values="Value" 
).reset_index()

# Step 4: Remove missing.

df_wide = df_wide.dropna(subset=[
    "Area harvested",
    "Yield",
    "Production"])

# Remove column axis name.
df_wide.columns.name = None

df_wide.head()

          Area               Item  Year  Area harvested  Production   Yield
0  Afghanistan  Almonds, in shell  2019         29203.0     38205.0  1308.3
1  Afghanistan  Almonds, in shell  2020         22134.0     39307.0  1775.9
2  Afghanistan  Almonds, in shell  2021         36862.0     64256.0  1743.2
3  Afghanistan  Almonds, in shell  2022         36462.0     63515.0  1742.0
4  Afghanistan  Almonds, in shell  2023         37000.0     67000.0  1810.8

In [ ]:
#  Check the data structure.

df_wide.info()
df_wide.describe()

<class 'pandas.DataFrame'>
Index: 44981 entries, 0 to 82125
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Area            44981 non-null  str
 1   Item            44981 non-null  str
 2   Year            44981 non-null  int64
 3   Area harvested  44981 non-null  float64
 4   Production      44981 non-null  float64
 5   Yield           44981 non-null  float64
dtypes: float64(3), int64(1), str(2)
memory usage: 2.4 MB

               Year  Area harvested    Production          Yield
count  44981.000000    4.498100e+04  4.498100e+04   44981.000000
mean    2021.005158    1.823420e+05  1.259761e+06   12583.616147
std        1.413843    1.474952e+06  1.307828e+07   26423.339156
min     2019.000000    0.000000e+00  0.000000e+00       0.000000
25%     2020.000000    4.740000e+02  2.177970e+03    1873.000000
50%     2021.000000    3.780000e+03  2.238800e+04    5892.100000
75%     2022.000000    2.679200e+04  1.645837e+05   14781.300000
max     2023.000000    4.783200e+07  7.825858e+08  705196.700000

In [ ]:
# Check the null values.

df_wide.isna().sum()

Area              0
Item              0
Year              0
Area harvested    0
Production        0
Yield             0
dtype: int64

In [ ]:
# Store the datas into the database.

from sqlalchemy import create_engine

engine = create_engine("postgresql://postgres:123456@localhost:5432/crop_data")

df_wide.to_sql('crop_data_cleaned',engine,if_exists='replace',index=False)

print("Data inserted to the SQL successfully")

Data inserted to the SQL successfully